- id: "Leopard: A General Test Suite for Isolation Level Verification"
  manual: true
  title: "Leopard: A General Test Suite for Isolation Level Verification"
  authors:
    - Peiyuan Liu
    - Siyang Weng
    - Keqiang Li
    - Lyu Ni
    - Chengcheng Yang
    - Rong Zhang
    - Weining Qian
    - Dian Qiao
  publisher: CIDR
  date: '2024-01-17'
- id: "Dike: A Benchmark Suite for Distributed Transactional Databases"
  manual: true
  title: "Dike: A Benchmark Suite for Distributed Transactional Databases"
  authors:
    - Huidong Zhang
    - Luyi Qu
    - Qingshuai Wang
    - Rong Zhang
    - Peng Cai
    - Quanqing Xu
    - Zhifeng Yang
    - Chuanhui Yang
  publisher: 2023 ACM SIGMOD/PODS International Conference on Management of Data (SIGMOD)
  date: '2023-01-01'
- id: "Leopard: A Black-Box Approach for Efficiently Verifying Various Isolation Levels"
  manual: true
  title: "Leopard: A Black-Box Approach for Efficiently Verifying Various Isolation Levels"
  authors:
    - Keqiang Li
    - Siyang Weng
    - Peiyuan Liu
    - Lyu Ni
    - Chengcheng Yang
    - Rong Zhang
    - Xuan Zhou
    - Jianghang Lou
    - Gui Huang
    - Weining Qian
    - Aoying Zhou
  publisher: 2023 IEEE International Conference on Data Engineering (ICDE)
  date: '2023-01-01'
- id: doi:10.1109/TKDE.2022.3153651
  title: A Scalable Query-Aware Enormous Database Generator for Database Evaluation
  publisher: IEEE Transactions on Knowledge and Data Engineering
  authors:
    - Qingshuai Wang
    - Yuming Li
    - Rong Zhang
    - Ke Shu
    - Zhenjie Zhang
    - Aoying Zhou
  image: /illustration/paper.touchstone.2.png
  date: '2022-01-01'
  extra-links:
    - type: source
      link: https://github.com/DBHammer/Touchstone
  tags:
    - Query-aware Data Generator
    - OLAP Database Testing
    - Query Generator

- id: url:https://www.usenix.org/conference/atc18/presentation/li-yuming
  title: 'Touchstone: Generating Enormous Query-Aware Test Databases'
  publisher: 2018 USENIX Annual Technical Conference (USENIX ATC 18)
  image: /illustration/paper.touchstone.1.png
  repo: DBHammer/Touchstone
  extra-links:
    - type: source
      link: https://github.com/DBHammer/Touchstone

- id: doi:10.1016/j.tbench.2022.100031
  image: /illustration/AreCurrentBenchmark.jpg
  extra-links:

- id: doi:10.48550/arXiv.1912.07172
  image: /illustration/lauca.png

- id: doi:10.1007/s11704-020-0248-x
- id: doi:10.1007/s11704-022-1056-2
- id: doi:10.1109/ICDE53745.2022.00036
- id: doi:10.1109/TKDE.2019.2947055
- id: doi:10.1007/978-3-030-85896-4_15
- id: doi:10.1142/11709
- id: doi:10.1007/s11704-019-8438-0
- id: doi:10.1007/978-3-030-60290-1_8
- id: doi:10.1007/978-3-030-60290-1_34
- id: doi:10.1007/978-3-030-71058-3_5
- id: doi:10.1007/s11280-018-0656-0
- id: doi:10.1007/978-3-030-26075-0_15
- id: doi:10.1007/s11704-016-6194-y
- id: doi:10.1109/TPDS.2018.2827380
- id: doi:10.1007/978-3-030-32813-9_13
- id: doi:10.1007/978-3-319-91458-9_52
- id: doi:10.1007/s11280-017-0431-7
- id: doi:10.1007/978-3-319-55699-4_39
- id: doi:10.1145/3078597.3078613
- id: doi:10.1007/s10115-015-0880-1
- id: doi:10.1007/978-3-319-45817-5_1
- id: doi:10.1007/978-3-319-45814-4_2
- id: doi:10.1145/2983323.2983705
- id: doi:10.1145/2983323.2983773
- id: doi:10.1007/978-3-319-39958-4_7
- id: doi:10.1007/978-3-319-48740-3_35
- id: doi:10.1145/2872518.2889348
  title: 'NERank: Ranking Named Entities in Document Collections'
- id: doi:10.1007/s11704-014-3492-0
- id: doi:10.1007/s11280-014-0296-y
- id: doi:10.1109/WISA.2015.63
- id: doi:10.1007/978-3-319-19548-3_29
- id: doi:10.1007/978-3-319-28121-6_15
- id: doi:10.1007/978-3-319-25255-1_42
- id: doi:10.1007/978-3-319-25255-1_51
- id: doi:10.1007/978-3-319-18123-3_33
- id: doi:10.1109/ICDEW.2015.7129545
- id: doi:10.1109/ICDE.2015.7113308
- id: doi:10.1007/978-3-319-21042-1_20
- id: doi:10.1007/978-3-319-21042-1_30
- id: doi:10.1007/978-3-319-21042-1_48
- id: doi:10.1002/dac.2619
- id: doi:10.1109/ASONAM.2014.6921558
- id: doi:10.1007/978-3-319-05810-8_27
- id: doi:10.1007/978-3-319-05813-9_36
- id: doi:10.1007/s11704-013-1256-x
- id: doi:10.1007/978-3-642-37401-2_70
- id: doi:10.1007/978-3-642-37450-0_28
- id: doi:10.1109/ICDM.2013.62
- id: doi:10.1007/978-3-642-39527-7_37
- id: doi:10.1007/978-3-642-41230-1_46
- id: doi:10.1109/CGC.2012.11
- id: doi:10.1145/2396761.2398591
- id: doi:10.1145/2187980.2188171
- id: doi:10.1007/978-3-642-20149-3_31
- id: doi:10.1109/IUCS.2010.5666772
- id: doi:10.1109/SKG.2010.18
- id: doi:10.1109/SKG.2010.19
- id: doi:10.1007/978-3-642-14246-8_36
- id: doi:10.1016/j.future.2008.02.010
- id: doi:10.1145/1667780.1667834
  title: "SOBEX: distributed service search engine that exploits service collaboration context"
- id: doi:10.1109/SKG.2009.89
- id: doi:10.1016/j.datak.2008.06.013
- id: doi:10.1007/s11704-008-0025-8
- id: doi:10.1109/ICDE.2008.4497617
- id: doi:10.1007/978-3-540-71703-4_7
  date: '2007-01-01'
- id: doi:10.4108/infoscale.2007.908
- id: doi:10.1109/ICDE.2006.169
- id: doi:10.1145/1142473.1142475
- id: HTAP数据库系统数据共享模型与优化策略
  manual: true
  title: HTAP数据库系统数据共享模型与优化策略
  publisher:
    软件学报
  authors:
    - 胡梓锐
    - 翁思扬
    - 俞融
    - 徐金凯
    - 王清帅
    - 张蓉
    - 周烜
  date: '2023-07-12'
- id: 面向复杂查询的可扩展应用场景生成
  manual: true
  title: 面向复杂查询的可扩展应用场景生成
  publisher:
    第39届CCF中国数据库学术会议 (NDBC 2022)
  authors:
    - 李好
    - 王清帅
    - 张蓉
    - 钱卫宁
  date: '2022-08-20'
- id: 分布式数据流上的高性能分发策略
  manual: true
  title: 分布式数据流上的高性能分发策略
  publisher:
    软件学报
  authors:
    - 房俊华
    - 王晓桐
    - 张蓉
    - 周傲英
  date: '2016-01-01'
- id: 考虑观点多样性的评论选择问题
  manual: true
  title: 考虑观点多样性的评论选择问题
  publisher:
    计算机研究与发展
  authors:
    - 余文喆
    - 沙朝锋
    - 何晓丰
    - 张蓉
  date: '2015-05-15'
- id: 电子商务商品归一化方法研究
  manual: true
  title: 电子商务商品归一化方法研究
  publisher:
    计算机学报
  authors:
    - 王立
    - 张蓉
    - 沙朝锋
    - 王晓玲
    - 周傲英
  date: '2014-01-01'
- id: 电子商务系统中的商品推荐系统
  manual: true
  title: 电子商务系统中的商品推荐系统
  publisher:
    华东师范大学学报
  authors:
    - 余文喆
    - 张蓉
    - 王立
  date: '2013-01-01'
- id: 一种支持多维数据范围查询的对等计算索引框架
  manual: true
  title: 一种支持多维数据范围查询的对等计算索引框架
  publisher:
    计算机研究与发展
  authors:
    - 张蓉
    - 钱卫宁
    - 周傲英
  date: '2009-01-01'
- id: 大规模分布式系统中的多属性查询处理
  manual: true
  title: 大规模分布式系统中的多属性查询处理
  publisher:
    计算机学报
  authors:
    - 周傲英
    - 周敏奇
    - 钱卫宁
    - 张蓉
  date: '2008-01-01'
- id: 一站式服务推荐系统
  manual: true
  title: 一站式服务推荐系统
  publisher:
    NDBC 2014
  authors:
    - 高祎璠
    - 郑芷凌
    - 余文喆
    - 程文亮
    - 张蓉
  date: '2014-01-01'